In [3]:
import pandas as pd

df = pd.read_excel(r"E:\DebugShala\Machine learning\6 ML intro_superviesd_unsup_&_Regression\Life_Expectancy_Data.xls")
df.head()

,Country,Year,Status,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,...,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
0,Afghanistan,2015,Developing,65.0,263.0,62,0.01,71.279624,65.0,1154,...,6.0,8.16,65.0,0.1,584.259210,33736494.0,17.2,17.3,0.479,10.1
1,Afghanistan,2014,Developing,59.9,271.0,64,0.01,73.523582,62.0,492,...,58.0,8.18,62.0,0.1,612.696514,327582.0,17.5,17.5,0.476,10.0
2,Afghanistan,2013,Developing,59.9,268.0,66,0.01,73.219243,64.0,430,...,62.0,8.13,64.0,0.1,631.744976,31731688.0,17.7,17.7,0.470,9.9
3,Afghanistan,2012,Developing,59.5,272.0,69,0.01,78.184215,67.0,2787,...,67.0,8.52,67.0,0.1,669.959000,3696958.0,17.9,18.0,0.463,9.8
4,Afghanistan,2011,Developing,59.2,275.0,71,0.01,7.097109,68.0,3013,...,68.0,7.87,68.0,0.1,63.537231,2978599.0,18.2,18.2,0.454,9.5

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2938 entries, 0 to 2937
Data columns (total 22 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Country                          2938 non-null   object
 1   Year                             2938 non-null   int64
 2   Status                           2938 non-null   object
 3   Life expectancy                  2928 non-null   float64
 4   Adult Mortality                  2928 non-null   float64
 5   infant deaths                    2938 non-null   int64
 6   Alcohol                          2744 non-null   float64
 7   percentage expenditure           2938 non-null   float64
 8   Hepatitis B                      2385 non-null   float64
 9   Measles                          2938 non-null   int64
 10   BMI                             2904 non-null   float64
 11  under-five deaths                2938 non-null   int64
 12  Polio                            2919 non-null   float64
 13  Total expenditure                2712 non-null   float64
 14  Diphtheria                       2919 non-null   float64
 15   HIV/AIDS                        2938 non-null   float64
 16  GDP                              2490 non-null   float64
 17  Population                       2286 non-null   float64
 18   thinness  1-19 years            2904 non-null   float64
 19   thinness 5-9 years              2904 non-null   float64
 20  Income composition of resources  2771 non-null   float64
 21  Schooling                        2775 non-null   float64
dtypes: float64(16), int64(4), object(2)
memory usage: 505.1+ KB

In [17]:
df.shape

(2938, 22)

In [4]:
df.columns

Index(['Country', 'Year', 'Status', 'Life expectancy ', 'Adult Mortality',
       'infant deaths', 'Alcohol', 'percentage expenditure', 'Hepatitis B',
       'Measles ', ' BMI ', 'under-five deaths ', 'Polio', 'Total expenditure',
       'Diphtheria ', ' HIV/AIDS', 'GDP', 'Population',
       ' thinness  1-19 years', ' thinness 5-9 years',
       'Income composition of resources', 'Schooling'],
      dtype='object')

In [6]:
# shuffling the target column into last place
df1 = df.reindex(columns=['Country', 'Year', 'Status', 'Adult Mortality',
       'infant deaths', 'Alcohol', 'percentage expenditure', 'Hepatitis B',
       'Measles ', ' BMI ', 'under-five deaths ', 'Polio', 'Total expenditure',
       'Diphtheria ', ' HIV/AIDS', 'GDP', 'Population',
       ' thinness  1-19 years', ' thinness 5-9 years',
       'Income composition of resources', 'Schooling','Life expectancy '])
df1.head()

,Country,Year,Status,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,BMI,...,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling,Life expectancy
0,Afghanistan,2015,Developing,263.0,62,0.01,71.279624,65.0,1154,19.1,...,8.16,65.0,0.1,584.259210,33736494.0,17.2,17.3,0.479,10.1,65.0
1,Afghanistan,2014,Developing,271.0,64,0.01,73.523582,62.0,492,18.6,...,8.18,62.0,0.1,612.696514,327582.0,17.5,17.5,0.476,10.0,59.9
2,Afghanistan,2013,Developing,268.0,66,0.01,73.219243,64.0,430,18.1,...,8.13,64.0,0.1,631.744976,31731688.0,17.7,17.7,0.470,9.9,59.9
3,Afghanistan,2012,Developing,272.0,69,0.01,78.184215,67.0,2787,17.6,...,8.52,67.0,0.1,669.959000,3696958.0,17.9,18.0,0.463,9.8,59.5
4,Afghanistan,2011,Developing,275.0,71,0.01,7.097109,68.0,3013,17.2,...,7.87,68.0,0.1,63.537231,2978599.0,18.2,18.2,0.454,9.5,59.2

In [7]:
# dealing with cat_columns
cat_col = ["Country","Status"]

from sklearn.preprocessing import LabelEncoder
lb = LabelEncoder()
for i in cat_col:
    df1[i] = lb.fit_transform(df1[i])

In [8]:
# dealing with continuous columns
con_col = ['Year', 'Adult Mortality',
       'infant deaths', 'Alcohol', 'percentage expenditure', 'Hepatitis B',
       'Measles ', ' BMI ', 'under-five deaths ', 'Polio', 'Total expenditure',
       'Diphtheria ', ' HIV/AIDS', 'GDP', 'Population',
       ' thinness  1-19 years', ' thinness 5-9 years',
       'Income composition of resources', 'Schooling']
from sklearn.preprocessing import MinMaxScaler
mm = MinMaxScaler()
for i in con_col:
    df1[i] = mm.fit_transform(df[i].values.reshape(-1,1))

In [9]:
df1.head()

,Country,Year,Status,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,BMI,...,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling,Life expectancy
0,0,1.000000,1,0.362881,0.034444,0.0,0.003659,0.653061,0.005439,0.209733,...,0.452118,0.649485,0.0,0.004889,0.026074,0.619565,0.603509,0.505274,0.487923,65.0
1,0,0.933333,1,0.373961,0.035556,0.0,0.003774,0.622449,0.002319,0.203940,...,0.453279,0.618557,0.0,0.005127,0.000253,0.630435,0.610526,0.502110,0.483092,59.9
2,0,0.866667,1,0.369806,0.036667,0.0,0.003759,0.642857,0.002027,0.198146,...,0.450377,0.639175,0.0,0.005287,0.024525,0.637681,0.617544,0.495781,0.478261,59.9
3,0,0.800000,1,0.375346,0.038333,0.0,0.004014,0.673469,0.013135,0.192352,...,0.473012,0.670103,0.0,0.005608,0.002857,0.644928,0.628070,0.488397,0.473430,59.5
4,0,0.733333,1,0.379501,0.039444,0.0,0.000364,0.683673,0.014200,0.187717,...,0.435287,0.680412,0.0,0.000519,0.002302,0.655797,0.635088,0.478903,0.458937,59.2

In [20]:
df1.isna().sum()

Country                              0
Year                                 0
Status                               0
Adult Mortality                     10
infant deaths                        0
Alcohol                            194
percentage expenditure               0
Hepatitis B                        553
Measles                              0
 BMI                                34
under-five deaths                    0
Polio                               19
Total expenditure                  226
Diphtheria                          19
 HIV/AIDS                            0
GDP                                448
Population                         652
 thinness  1-19 years               34
 thinness 5-9 years                 34
Income composition of resources    167
Schooling                          163
Life expectancy                     10
dtype: int64

In [25]:
df1.columns[df1.isnull().any()] # have a look on columns which have null values

Index(['Adult Mortality', 'Alcohol', 'Hepatitis B', ' BMI ', 'Polio',
       'Total expenditure', 'Diphtheria ', 'GDP', 'Population',
       ' thinness  1-19 years', ' thinness 5-9 years',
       'Income composition of resources', 'Schooling', 'Life expectancy '],
      dtype='object')

### Filling Null Values

In [12]:
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(strategy='mean')
imputer.fit(df1)

SimpleImputer()

In [35]:
df1_imputed = pd.DataFrame(imputer.transform(df1), columns=df1.columns)
df1_imputed.head()

,Country,Year,Status,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,BMI,...,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling,Life expectancy
0,0.0,1.000000,1.0,0.362881,0.034444,0.0,0.003659,0.653061,0.005439,0.209733,...,0.452118,0.649485,0.0,0.004889,0.026074,0.619565,0.603509,0.505274,0.487923,65.0
1,0.0,0.933333,1.0,0.373961,0.035556,0.0,0.003774,0.622449,0.002319,0.203940,...,0.453279,0.618557,0.0,0.005127,0.000253,0.630435,0.610526,0.502110,0.483092,59.9
2,0.0,0.866667,1.0,0.369806,0.036667,0.0,0.003759,0.642857,0.002027,0.198146,...,0.450377,0.639175,0.0,0.005287,0.024525,0.637681,0.617544,0.495781,0.478261,59.9
3,0.0,0.800000,1.0,0.375346,0.038333,0.0,0.004014,0.673469,0.013135,0.192352,...,0.473012,0.670103,0.0,0.005608,0.002857,0.644928,0.628070,0.488397,0.473430,59.5
4,0.0,0.733333,1.0,0.379501,0.039444,0.0,0.000364,0.683673,0.014200,0.187717,...,0.435287,0.680412,0.0,0.000519,0.002302,0.655797,0.635088,0.478903,0.458937,59.2

In [36]:
print(df1_imputed.isna().sum())

Country                            0
Year                               0
Status                             0
Adult Mortality                    0
infant deaths                      0
Alcohol                            0
percentage expenditure             0
Hepatitis B                        0
Measles                            0
 BMI                               0
under-five deaths                  0
Polio                              0
Total expenditure                  0
Diphtheria                         0
 HIV/AIDS                          0
GDP                                0
Population                         0
 thinness  1-19 years              0
 thinness 5-9 years                0
Income composition of resources    0
Schooling                          0
Life expectancy                    0
dtype: int64

In [37]:
df1_imputed.shape

(2938, 22)